// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_baseline
arma::vec rcpp_baseline(const NumericVector& y_vec, const double& lambda, const double& ratio);
RcppExport SEXP _arplsbaseline_rcpp_baseline(SEXP y_vecSEXP, SEXP lambdaSEXP, SEXP ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double& >::type ratio(ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_baseline(y_vec, lambda, ratio));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_arplsbaseline_rcpp_baseline", (DL_FUNC) &_arplsbaseline_rcpp_baseline, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_arplsbaseline(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
