# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_baseline <- function(y_vec, lambda, ratio) {
    .Call(`_arplsbaseline_rcpp_baseline`, y_vec, lambda, ratio)
}

